

INSERT INTO StateLookup (id,code,name) VALUES (2,'AL','Alabama');
INSERT INTO StateLookup (id,code,name) VALUES (3,'AK','Alaska');
INSERT INTO StateLookup (id,code,name) VALUES (4,'AR','Arkansas');
INSERT INTO StateLookup (id,code,name) VALUES (5,'AS','American Samoa');
INSERT INTO StateLookup (id,code,name) VALUES (6,'AZ','Arizona');
INSERT INTO StateLookup (id,code,name) VALUES (7,'CA','California');
INSERT INTO StateLookup (id,code,name) VALUES (8,'CO','Colorado');
INSERT INTO StateLookup (id,code,name) VALUES (9,'CT','Connecticut');
INSERT INTO StateLookup (id,code,name) VALUES (10,'DE','Delaware');
INSERT INTO StateLookup (id,code,name) VALUES (11,'DC','District of Columbia');
INSERT INTO StateLookup (id,code,name) VALUES (12,'FL','Florida');
INSERT INTO StateLookup (id,code,name) VALUES (13,'GA','Georgia');
INSERT INTO StateLookup (id,code,name) VALUES (14,'GU','Guam');
INSERT INTO StateLookup (id,code,name) VALUES (15,'HI','Hawaii');
INSERT INTO StateLookup (id,code,name) VALUES (16,'ID','Idaho');
INSERT INTO StateLookup (id,code,name) VALUES (17,'IL','Illinois');
INSERT INTO StateLookup (id,code,name) VALUES (18,'IO','Iowa');
INSERT INTO StateLookup (id,code,name) VALUES (19,'KS','Kansas');
INSERT INTO StateLookup (id,code,name) VALUES (20,'KY','Kentucky');
INSERT INTO StateLookup (id,code,name) VALUES (21,'LA','Louisiana');
INSERT INTO StateLookup (id,code,name) VALUES (22,'ME','Maine');
INSERT INTO StateLookup (id,code,name) VALUES (23,'MD','Maryland');
INSERT INTO StateLookup (id,code,name) VALUES (24,'MH','Marshall Islands');
INSERT INTO StateLookup (id,code,name) VALUES (25,'MA','Massachusetts');
INSERT INTO StateLookup (id,code,name) VALUES (26,'MI','Michigan');
INSERT INTO StateLookup (id,code,name) VALUES (27,'FM','Micronesia');
INSERT INTO StateLookup (id,code,name) VALUES (28,'MN','Minesota');
INSERT INTO StateLookup (id,code,name) VALUES (29,'MS','Mississippi');
INSERT INTO StateLookup (id,code,name) VALUES (30,'MO','Misouri');
INSERT INTO StateLookup (id,code,name) VALUES (31,'MT','Montana');
INSERT INTO StateLookup (id,code,name) VALUES (32,'NE','Nebraska');
INSERT INTO StateLookup (id,code,name) VALUES (33,'NV','Nevada');
INSERT INTO StateLookup (id,code,name) VALUES (34,'NH','New Hampshire');
INSERT INTO StateLookup (id,code,name) VALUES (35,'NJ','New Jersey');
INSERT INTO StateLookup (id,code,name) VALUES (36,'NM','New Mexico');
INSERT INTO StateLookup (id,code,name) VALUES (37,'NY','New York');
INSERT INTO StateLookup (id,code,name) VALUES (38,'NC','North Carolina');
INSERT INTO StateLookup (id,code,name) VALUES (39,'ND','North Dakota');
INSERT INTO StateLookup (id,code,name) VALUES (40,'MP','Northern Marianas');
INSERT INTO StateLookup (id,code,name) VALUES (41,'OH','Ohio');
INSERT INTO StateLookup (id,code,name) VALUES (42,'OK','Oklahoma');
INSERT INTO StateLookup (id,code,name) VALUES (43,'OR','Oregon');
INSERT INTO StateLookup (id,code,name) VALUES (44,'PW','Palau');
INSERT INTO StateLookup (id,code,name) VALUES (45,'PA','Pennsylvania');
INSERT INTO StateLookup (id,code,name) VALUES (46,'RI','Rhode Island');
INSERT INTO StateLookup (id,code,name) VALUES (47,'SC','South Carolina');
INSERT INTO StateLookup (id,code,name) VALUES (48,'SD','South Dakota');
INSERT INTO StateLookup (id,code,name) VALUES (49,'TN','Tennessee');
INSERT INTO StateLookup (id,code,name) VALUES (50,'TX','Texas');
INSERT INTO StateLookup (id,code,name) VALUES (51,'UT','Utah');
INSERT INTO StateLookup (id,code,name) VALUES (52,'VT','Vermont');
INSERT INTO StateLookup (id,code,name) VALUES (53,'VA','Virginia');
INSERT INTO StateLookup (id,code,name) VALUES (54,'VI','Vergin Islands');
INSERT INTO StateLookup (id,code,name) VALUES (55,'WA','Washington');
INSERT INTO StateLookup (id,code,name) VALUES (56,'WV','West Virginia');
INSERT INTO StateLookup (id,code,name) VALUES (57,'WI','Wisconsin');
INSERT INTO StateLookup (id,code,name) VALUES (58,'WY','Wyoming');
